
Technology:
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingagilequant-sp-z-oo.csv
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingalphaclone.csv
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingb-stock-solutions.csv
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingan-binh-commercial-joint-stock-bank-abbank.csv
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingalgoriz.csv
	-venturecapitalbyyearbytypeoftechcapitalraisemoney-raised-by-organizations-startups-from-venture-capital-vc-fundingabe-global.csv
	
